//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Web.Utils.Languages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class es_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es_ES() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Web.Utils.Languages.es-ES", typeof(es_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dominio ya licenciada.
        /// </summary>
        public static string AssetAlreadyLicensed {
            get {
                return ResourceManager.GetString("AssetAlreadyLicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dominio no encontrada.
        /// </summary>
        public static string AssetNotFound {
            get {
                return ResourceManager.GetString("AssetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lote no confirmado.
        /// </summary>
        public static string BatchNotConfirmed {
            get {
                return ResourceManager.GetString("BatchNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cj.
        /// </summary>
        public static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cajas.
        /// </summary>
        public static string Boxes {
            get {
                return ResourceManager.GetString("Boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cj/h.
        /// </summary>
        public static string BoxPerHour {
            get {
                return ResourceManager.GetString("BoxPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Roto.
        /// </summary>
        public static string Broken {
            get {
                return ResourceManager.GetString("Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoría.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmado.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agrietado.
        /// </summary>
        public static string Cracked {
            get {
                return ResourceManager.GetString("Cracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente no encontrado.
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ya existe un cliente con ese nombre.
        /// </summary>
        public static string CustomerWithSameNameError {
            get {
                return ResourceManager.GetString("CustomerWithSameNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a dd/MM/yyyy.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Los días de búsqueda no pueden ser diferentes.
        /// </summary>
        public static string DifferentDays {
            get {
                return ResourceManager.GetString("DifferentDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sucio.
        /// </summary>
        public static string Dirty {
            get {
                return ResourceManager.GetString("Dirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inactivo.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No responder.
        /// </summary>
        public static string DontReply {
            get {
                return ResourceManager.GetString("DontReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontró ninguna secadora.
        /// </summary>
        public static string DryerNotFound {
            get {
                return ResourceManager.GetString("DryerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe de producción.
        /// </summary>
        public static string EggResultsReportTitle {
            get {
                return ResourceManager.GetString("EggResultsReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Huevos.
        /// </summary>
        public static string Eggs {
            get {
                return ResourceManager.GetString("Eggs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Huevos producidos.
        /// </summary>
        public static string EggsProducedTitle {
            get {
                return ResourceManager.GetString("EggsProducedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontró ningún lavador de huevos.
        /// </summary>
        public static string EggWasherNotFound {
            get {
                return ResourceManager.GetString("EggWasherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Emergencia.
        /// </summary>
        public static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fecha final.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al aplicar filtros.
        /// </summary>
        public static string ErrorApplyingFilters {
            get {
                return ResourceManager.GetString("ErrorApplyingFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al comunicarse con el servicio externo.
        /// </summary>
        public static string ErrorCommunicatingWithExternalService {
            get {
                return ResourceManager.GetString("ErrorCommunicatingWithExternalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al borrar.
        /// </summary>
        public static string ErrorDeleting {
            get {
                return ResourceManager.GetString("ErrorDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al generar la clave de licencia.
        /// </summary>
        public static string ErrorGeneratingKey {
            get {
                return ResourceManager.GetString("ErrorGeneratingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al generar el archivo de informe.
        /// </summary>
        public static string ErrorGeneratingReportFile {
            get {
                return ResourceManager.GetString("ErrorGeneratingReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al generar la clave de autenticación.
        /// </summary>
        public static string ErrorGeneratingUserKey {
            get {
                return ResourceManager.GetString("ErrorGeneratingUserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al obtener la clave del dominio.
        /// </summary>
        public static string ErrorGettingAssetKey {
            get {
                return ResourceManager.GetString("ErrorGettingAssetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al cargar datos de huevos.
        /// </summary>
        public static string ErrorGettingEggResults {
            get {
                return ResourceManager.GetString("ErrorGettingEggResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al cargar programas de máquina.
        /// </summary>
        public static string ErrorGettingMachineSchedules {
            get {
                return ResourceManager.GetString("ErrorGettingMachineSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al obtener el esquema de planta.
        /// </summary>
        public static string ErrorGettingPlantSchema {
            get {
                return ResourceManager.GetString("ErrorGettingPlantSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al cargar datos de producción.
        /// </summary>
        public static string ErrorGettingProductionResults {
            get {
                return ResourceManager.GetString("ErrorGettingProductionResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al obtener la IP de la solicitud.
        /// </summary>
        public static string ErrorGettingRequestIp {
            get {
                return ResourceManager.GetString("ErrorGettingRequestIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al obtener información de la sesión.
        /// </summary>
        public static string ErrorGettingSessionInfo {
            get {
                return ResourceManager.GetString("ErrorGettingSessionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al iniciar sesión.
        /// </summary>
        public static string ErrorLoggingIn {
            get {
                return ResourceManager.GetString("ErrorLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al cerrar sesión.
        /// </summary>
        public static string ErrorLoggingOut {
            get {
                return ResourceManager.GetString("ErrorLoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al recibir la confirmación del lote.
        /// </summary>
        public static string ErrorReceivingBatchConfirm {
            get {
                return ResourceManager.GetString("ErrorReceivingBatchConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al recuperar la contraseña.
        /// </summary>
        public static string ErrorRecoveringPassword {
            get {
                return ResourceManager.GetString("ErrorRecoveringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al guardar.
        /// </summary>
        public static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al guardar las credenciale.
        /// </summary>
        public static string ErrorSavingCredentials {
            get {
                return ResourceManager.GetString("ErrorSavingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al enviar correo electrónico.
        /// </summary>
        public static string ErrorSendingEmail {
            get {
                return ResourceManager.GetString("ErrorSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al iniciar lote.
        /// </summary>
        public static string ErrorStartingBatch {
            get {
                return ResourceManager.GetString("ErrorStartingBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al detener el control de lotes.
        /// </summary>
        public static string ErrorStoppingBatchControl {
            get {
                return ResourceManager.GetString("ErrorStoppingBatchControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al actualizar.
        /// </summary>
        public static string ErrorUpdating {
            get {
                return ResourceManager.GetString("ErrorUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al actualizar el cambio.
        /// </summary>
        public static string ErrorUpdatingBatch {
            get {
                return ResourceManager.GetString("ErrorUpdatingBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al validar credenciales.
        /// </summary>
        public static string ErrorValidatingCredentials {
            get {
                return ResourceManager.GetString("ErrorValidatingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Los turnos no pueden ser los mismos.
        /// </summary>
        public static string ErrorValidatingShift {
            get {
                return ResourceManager.GetString("ErrorValidatingShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Extra.
        /// </summary>
        public static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error al obtener el documento de descripción.
        /// </summary>
        public static string FileDescriptionError {
            get {
                return ResourceManager.GetString("FileDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Viernes.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Industrial.
        /// </summary>
        public static string Industrial {
            get {
                return ResourceManager.GetString("Industrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salidas insuficientes.
        /// </summary>
        public static string InsufficientOutputs {
            get {
                return ResourceManager.GetString("InsufficientOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token de autenticación no válido.
        /// </summary>
        public static string InvalidAuthToken {
            get {
                return ResourceManager.GetString("InvalidAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lista de categorías no válida.
        /// </summary>
        public static string InvalidCategoryList {
            get {
                return ResourceManager.GetString("InvalidCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hay caracteres inválidos en la solicitud.
        /// </summary>
        public static string InvalidCharacters {
            get {
                return ResourceManager.GetString("InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ no válido.
        /// </summary>
        public static string InvalidCnpj {
            get {
                return ResourceManager.GetString("InvalidCnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Documento no válido.
        /// </summary>
        public static string InvalidDocument {
            get {
                return ResourceManager.GetString("InvalidDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Correo electrónico no válido.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IP inválida.
        /// </summary>
        public static string InvalidIp {
            get {
                return ResourceManager.GetString("InvalidIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Latitud y longitud no válidas.
        /// </summary>
        public static string InvalidLatitudeLongitude {
            get {
                return ResourceManager.GetString("InvalidLatitudeLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Licencia no válida.
        /// </summary>
        public static string InvalidLicense {
            get {
                return ResourceManager.GetString("InvalidLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clave de licencia no válida.
        /// </summary>
        public static string InvalidLicenseKey {
            get {
                return ResourceManager.GetString("InvalidLicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nombre no válido.
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Página no válida.
        /// </summary>
        public static string InvalidPage {
            get {
                return ResourceManager.GetString("InvalidPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contraseña no válida.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de recuperación no válido.
        /// </summary>
        public static string InvalidRecoveryCode {
            get {
                return ResourceManager.GetString("InvalidRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a El nombre de la parada programada no es válido.
        /// </summary>
        public static string InvalidScheduledStopName {
            get {
                return ResourceManager.GetString("InvalidScheduledStopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a El nombre de usuario no es válido.
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario o contraseña invalido.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a La contraseña de usuario no es válida.
        /// </summary>
        public static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código postal no válido.
        /// </summary>
        public static string InvalidZipCode {
            get {
                return ResourceManager.GetString("InvalidZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jumbo.
        /// </summary>
        public static string Jumbo {
            get {
                return ResourceManager.GetString("Jumbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grande.
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Diseño no encontrado.
        /// </summary>
        public static string LayoutNotFound {
            get {
                return ResourceManager.GetString("LayoutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agujereado.
        /// </summary>
        public static string Leaked {
            get {
                return ResourceManager.GetString("Leaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error de celda de carga.
        /// </summary>
        public static string LoadCellError {
            get {
                return ResourceManager.GetString("LoadCellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontró ningún modelo.
        /// </summary>
        public static string ModelNotFound {
            get {
                return ResourceManager.GetString("ModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lunes.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontró contexto.
        /// </summary>
        public static string NoContextFound {
            get {
                return ResourceManager.GetString("NoContextFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontró ningún cliente.
        /// </summary>
        public static string NoCustomersFound {
            get {
                return ResourceManager.GetString("NoCustomersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontraron categorías de huevo.
        /// </summary>
        public static string NoEggCategoriesFound {
            get {
                return ResourceManager.GetString("NoEggCategoriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontró ninguna licencia.
        /// </summary>
        public static string NoLicenseFound {
            get {
                return ResourceManager.GetString("NoLicenseFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontró ninguna máquina.
        /// </summary>
        public static string NoMachineFound {
            get {
                return ResourceManager.GetString("NoMachineFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontró ninguna operación de máquina.
        /// </summary>
        public static string NoMachineOperationFound {
            get {
                return ResourceManager.GetString("NoMachineOperationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontró tiempo.
        /// </summary>
        public static string NoMachineScheduleFound {
            get {
                return ResourceManager.GetString("NoMachineScheduleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontraron turnos.
        /// </summary>
        public static string NoShiftFound {
            get {
                return ResourceManager.GetString("NoShiftFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontró ningún horario semanal.
        /// </summary>
        public static string NoWeekScheduledFound {
            get {
                return ResourceManager.GetString("NoWeekScheduledFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Apagado.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operación.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a La contraseña debe contener al menos una letra minúscula y una mayúscula.
        /// </summary>
        public static string PasswordMustContainUppercaseAndLowercase {
            get {
                return ResourceManager.GetString("PasswordMustContainUppercaseAndLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a La contraseña debe tener al menos un carácter especial.
        /// </summary>
        public static string PasswordMustHaveSpecialCharacter {
            get {
                return ResourceManager.GetString("PasswordMustHaveSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a La contraseña debe tener entre 8 y 50 caracteres.
        /// </summary>
        public static string PasswordMustHaveValidLength {
            get {
                return ResourceManager.GetString("PasswordMustHaveValidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recuperación de contraseña.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Las contraseñas no son iguales.
        /// </summary>
        public static string PasswordsAreNotTheSame {
            get {
                return ResourceManager.GetString("PasswordsAreNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontró ninguna planta.
        /// </summary>
        public static string PlantNotFound {
            get {
                return ResourceManager.GetString("PlantNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ya existe una planta con este CNPJ.
        /// </summary>
        public static string PlantWithSameCnpjError {
            get {
                return ResourceManager.GetString("PlantWithSameCnpjError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ya existe una planta con este nombre.
        /// </summary>
        public static string PlantWithSameNameError {
            get {
                return ResourceManager.GetString("PlantWithSameNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Producto no encontrado.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cantidad.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rojo.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro no encontrado.
        /// </summary>
        public static string RegisterNotFound {
            get {
                return ResourceManager.GetString("RegisterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tiempo restante.
        /// </summary>
        public static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Los lotes no pueden ser iguales.
        /// </summary>
        public static string SameBatchError {
            get {
                return ResourceManager.GetString("SameBatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sábado.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escala.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Paradas programadas.
        /// </summary>
        public static string ScheduledStop {
            get {
                return ResourceManager.GetString("ScheduledStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Las horas de parada programadas entran en conflicto con otra parada.
        /// </summary>
        public static string ScheduledStopConflict {
            get {
                return ResourceManager.GetString("ScheduledStopConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turno A.
        /// </summary>
        public static string ShiftA {
            get {
                return ResourceManager.GetString("ShiftA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turno B.
        /// </summary>
        public static string ShiftB {
            get {
                return ResourceManager.GetString("ShiftB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turno C.
        /// </summary>
        public static string ShiftC {
            get {
                return ResourceManager.GetString("ShiftC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Los horarios de los turnos entran en conflicto con otro turno.
        /// </summary>
        public static string ShiftConflict {
            get {
                return ResourceManager.GetString("ShiftConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turno D.
        /// </summary>
        public static string ShiftD {
            get {
                return ResourceManager.GetString("ShiftD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pequeño.
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solenoide.
        /// </summary>
        public static string Solenoid {
            get {
                return ResourceManager.GetString("Solenoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error de solenoide.
        /// </summary>
        public static string SolenoidError {
            get {
                return ResourceManager.GetString("SolenoidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maquina parada.
        /// </summary>
        public static string StandBy {
            get {
                return ResourceManager.GetString("StandBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fecha de inicio.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a La fecha de inicio no puede ser posterior a la fecha de finalización.
        /// </summary>
        public static string StartDateGreaterThanEndDate {
            get {
                return ResourceManager.GetString("StartDateGreaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comenzó.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maquina parada.
        /// </summary>
        public static string StoppedMachine {
            get {
                return ResourceManager.GetString("StoppedMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ningún nombre puede exceder los 15 caracteres.
        /// </summary>
        public static string StringLengthValidation {
            get {
                return ResourceManager.GetString("StringLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Domingo.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Super jumbo.
        /// </summary>
        public static string SuperJumbo {
            get {
                return ResourceManager.GetString("SuperJumbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jueves.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Demasiadas solicitudes a la API. Por favor, espere un momento.
        /// </summary>
        public static string TooManyRequestsWaitAMoment {
            get {
                return ResourceManager.GetString("TooManyRequestsWaitAMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total de cajas.
        /// </summary>
        public static string TotalBoxesQuantity {
            get {
                return ResourceManager.GetString("TotalBoxesQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Datos generales.
        /// </summary>
        public static string TotalEggsDataTitle {
            get {
                return ResourceManager.GetString("TotalEggsDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total de huevos.
        /// </summary>
        public static string TotalEggsQuantity {
            get {
                return ResourceManager.GetString("TotalEggsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total de producción de la máquina.
        /// </summary>
        public static string TotalMachineProducing {
            get {
                return ResourceManager.GetString("TotalMachineProducing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total de paradas no programadas.
        /// </summary>
        public static string TotalUnscheduledDowntime {
            get {
                return ResourceManager.GetString("TotalUnscheduledDowntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso total.
        /// </summary>
        public static string TotalWeight {
            get {
                return ResourceManager.GetString("TotalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Martes.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Paradas no programadas.
        /// </summary>
        public static string UnscheduledStop {
            get {
                return ResourceManager.GetString("UnscheduledStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario no encontrado.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario guardado exitosamente.
        /// </summary>
        public static string UserSavedSuccessfully {
            get {
                return ResourceManager.GetString("UserSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a La sesión del usuario ha caducado.
        /// </summary>
        public static string UserSessionExpired {
            get {
                return ResourceManager.GetString("UserSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario sin permisos.
        /// </summary>
        public static string UserWithoutPermission {
            get {
                return ResourceManager.GetString("UserWithoutPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ya existe un usuario con este documento.
        /// </summary>
        public static string UserWithSameDocumentError {
            get {
                return ResourceManager.GetString("UserWithSameDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ya existe un usuario con este correo electrónico.
        /// </summary>
        public static string UserWithSameEmailError {
            get {
                return ResourceManager.GetString("UserWithSameEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ya existe un usuario con esta clave.
        /// </summary>
        public static string UserWithSameKeyError {
            get {
                return ResourceManager.GetString("UserWithSameKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token válido ya generado.
        /// </summary>
        public static string ValidTokenAlreadyGenerated {
            get {
                return ResourceManager.GetString("ValidTokenAlreadyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se encontró ningún sistema de visión.
        /// </summary>
        public static string VisionSystemNotFound {
            get {
                return ResourceManager.GetString("VisionSystemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sistema de visión.
        /// </summary>
        public static string VisionSystemTitle {
            get {
                return ResourceManager.GetString("VisionSystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Espere cinco minutos para enviar el correo electrónico nuevamente.
        /// </summary>
        public static string WaitFiveMinutesToSendEmailAgain {
            get {
                return ResourceManager.GetString("WaitFiveMinutesToSendEmailAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Miércoles.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Blanco.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tu código de recuperación es.
        /// </summary>
        public static string YourRecoveryCodeIs {
            get {
                return ResourceManager.GetString("YourRecoveryCodeIs", resourceCulture);
            }
        }
    }
}
