//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Web.Utils.Languages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Web.Utils.Languages.zh-CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 域已许可.
        /// </summary>
        public static string AssetAlreadyLicensed {
            get {
                return ResourceManager.GetString("AssetAlreadyLicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到域.
        /// </summary>
        public static string AssetNotFound {
            get {
                return ResourceManager.GetString("AssetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 批次未确认.
        /// </summary>
        public static string BatchNotConfirmed {
            get {
                return ResourceManager.GetString("BatchNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 箱.
        /// </summary>
        public static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 箱子数量.
        /// </summary>
        public static string Boxes {
            get {
                return ResourceManager.GetString("Boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 箱/时.
        /// </summary>
        public static string BoxPerHour {
            get {
                return ResourceManager.GetString("BoxPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 破蛋.
        /// </summary>
        public static string Broken {
            get {
                return ResourceManager.GetString("Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 类别.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 确认.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 裂纹蛋.
        /// </summary>
        public static string Cracked {
            get {
                return ResourceManager.GetString("Cracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到客户.
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 已经有一个客户使用该名称.
        /// </summary>
        public static string CustomerWithSameNameError {
            get {
                return ResourceManager.GetString("CustomerWithSameNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 年-月-日.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 搜索天数不能不同.
        /// </summary>
        public static string DifferentDays {
            get {
                return ResourceManager.GetString("DifferentDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 脏蛋.
        /// </summary>
        public static string Dirty {
            get {
                return ResourceManager.GetString("Dirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 禁用.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 请勿回复.
        /// </summary>
        public static string DontReply {
            get {
                return ResourceManager.GetString("DontReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到烘干机.
        /// </summary>
        public static string DryerNotFound {
            get {
                return ResourceManager.GetString("DryerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 生产报告.
        /// </summary>
        public static string EggResultsReportTitle {
            get {
                return ResourceManager.GetString("EggResultsReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 鸡蛋.
        /// </summary>
        public static string Eggs {
            get {
                return ResourceManager.GetString("Eggs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 生产的鸡蛋.
        /// </summary>
        public static string EggsProducedTitle {
            get {
                return ResourceManager.GetString("EggsProducedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到蛋洗机.
        /// </summary>
        public static string EggWasherNotFound {
            get {
                return ResourceManager.GetString("EggWasherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 紧急情况.
        /// </summary>
        public static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 结束日期.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 应用过滤器时出错.
        /// </summary>
        public static string ErrorApplyingFilters {
            get {
                return ResourceManager.GetString("ErrorApplyingFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 与外部服务通信时出错.
        /// </summary>
        public static string ErrorCommunicatingWithExternalService {
            get {
                return ResourceManager.GetString("ErrorCommunicatingWithExternalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 删除时出错.
        /// </summary>
        public static string ErrorDeleting {
            get {
                return ResourceManager.GetString("ErrorDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 生成许可证密钥时出错.
        /// </summary>
        public static string ErrorGeneratingKey {
            get {
                return ResourceManager.GetString("ErrorGeneratingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 生成报告文件时出错.
        /// </summary>
        public static string ErrorGeneratingReportFile {
            get {
                return ResourceManager.GetString("ErrorGeneratingReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 生成身份验证密钥时出错.
        /// </summary>
        public static string ErrorGeneratingUserKey {
            get {
                return ResourceManager.GetString("ErrorGeneratingUserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 获取域密钥时出错.
        /// </summary>
        public static string ErrorGettingAssetKey {
            get {
                return ResourceManager.GetString("ErrorGettingAssetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 加载鸡蛋数据时出错.
        /// </summary>
        public static string ErrorGettingEggResults {
            get {
                return ResourceManager.GetString("ErrorGettingEggResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 加载计算机程序时出错.
        /// </summary>
        public static string ErrorGettingMachineSchedules {
            get {
                return ResourceManager.GetString("ErrorGettingMachineSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 获取工厂模式时出错.
        /// </summary>
        public static string ErrorGettingPlantSchema {
            get {
                return ResourceManager.GetString("ErrorGettingPlantSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 加载生产数据时出错.
        /// </summary>
        public static string ErrorGettingProductionResults {
            get {
                return ResourceManager.GetString("ErrorGettingProductionResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 获取请求 IP 时出错.
        /// </summary>
        public static string ErrorGettingRequestIp {
            get {
                return ResourceManager.GetString("ErrorGettingRequestIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 获取会话信息时出错.
        /// </summary>
        public static string ErrorGettingSessionInfo {
            get {
                return ResourceManager.GetString("ErrorGettingSessionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 登录时出错.
        /// </summary>
        public static string ErrorLoggingIn {
            get {
                return ResourceManager.GetString("ErrorLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 退出登录时出错.
        /// </summary>
        public static string ErrorLoggingOut {
            get {
                return ResourceManager.GetString("ErrorLoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 接收批次确认时出错.
        /// </summary>
        public static string ErrorReceivingBatchConfirm {
            get {
                return ResourceManager.GetString("ErrorReceivingBatchConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 恢复密码时出错.
        /// </summary>
        public static string ErrorRecoveringPassword {
            get {
                return ResourceManager.GetString("ErrorRecoveringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 保存时出错.
        /// </summary>
        public static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 保存凭据时出错.
        /// </summary>
        public static string ErrorSavingCredentials {
            get {
                return ResourceManager.GetString("ErrorSavingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 发送电子邮件时出错.
        /// </summary>
        public static string ErrorSendingEmail {
            get {
                return ResourceManager.GetString("ErrorSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 启动批处理时出错.
        /// </summary>
        public static string ErrorStartingBatch {
            get {
                return ResourceManager.GetString("ErrorStartingBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 停止批处理控制时出错.
        /// </summary>
        public static string ErrorStoppingBatchControl {
            get {
                return ResourceManager.GetString("ErrorStoppingBatchControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 更新时出错.
        /// </summary>
        public static string ErrorUpdating {
            get {
                return ResourceManager.GetString("ErrorUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 更新班次时出错.
        /// </summary>
        public static string ErrorUpdatingBatch {
            get {
                return ResourceManager.GetString("ErrorUpdatingBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 验证凭据时出错.
        /// </summary>
        public static string ErrorValidatingCredentials {
            get {
                return ResourceManager.GetString("ErrorValidatingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 班次不能相同.
        /// </summary>
        public static string ErrorValidatingShift {
            get {
                return ResourceManager.GetString("ErrorValidatingShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Extra.
        /// </summary>
        public static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 获取描述文档时出错.
        /// </summary>
        public static string FileDescriptionError {
            get {
                return ResourceManager.GetString("FileDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 星期五.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 工业蛋.
        /// </summary>
        public static string Industrial {
            get {
                return ResourceManager.GetString("Industrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 输出不足.
        /// </summary>
        public static string InsufficientOutputs {
            get {
                return ResourceManager.GetString("InsufficientOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 无效的身份验证令牌.
        /// </summary>
        public static string InvalidAuthToken {
            get {
                return ResourceManager.GetString("InvalidAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 类别列表无效.
        /// </summary>
        public static string InvalidCategoryList {
            get {
                return ResourceManager.GetString("InvalidCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 请求中包含无效字符.
        /// </summary>
        public static string InvalidCharacters {
            get {
                return ResourceManager.GetString("InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 无效的CNPJ.
        /// </summary>
        public static string InvalidCnpj {
            get {
                return ResourceManager.GetString("InvalidCnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 无效文档.
        /// </summary>
        public static string InvalidDocument {
            get {
                return ResourceManager.GetString("InvalidDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 无效的电子邮件.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 无效的IP.
        /// </summary>
        public static string InvalidIp {
            get {
                return ResourceManager.GetString("InvalidIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 无效的纬度和经度.
        /// </summary>
        public static string InvalidLatitudeLongitude {
            get {
                return ResourceManager.GetString("InvalidLatitudeLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 无效许可证.
        /// </summary>
        public static string InvalidLicense {
            get {
                return ResourceManager.GetString("InvalidLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 无效的许可证密钥.
        /// </summary>
        public static string InvalidLicenseKey {
            get {
                return ResourceManager.GetString("InvalidLicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 无效名称.
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 无效页面.
        /// </summary>
        public static string InvalidPage {
            get {
                return ResourceManager.GetString("InvalidPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 无效密码.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 无效的恢复代码.
        /// </summary>
        public static string InvalidRecoveryCode {
            get {
                return ResourceManager.GetString("InvalidRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 计划的站点名称无效.
        /// </summary>
        public static string InvalidScheduledStopName {
            get {
                return ResourceManager.GetString("InvalidScheduledStopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 用户名无效.
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 用户名或密码无效.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 用户密码无效.
        /// </summary>
        public static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 无效的邮政编码.
        /// </summary>
        public static string InvalidZipCode {
            get {
                return ResourceManager.GetString("InvalidZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 特大号.
        /// </summary>
        public static string Jumbo {
            get {
                return ResourceManager.GetString("Jumbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 大号.
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到布局.
        /// </summary>
        public static string LayoutNotFound {
            get {
                return ResourceManager.GetString("LayoutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 流清蛋.
        /// </summary>
        public static string Leaked {
            get {
                return ResourceManager.GetString("Leaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 传感器误差.
        /// </summary>
        public static string LoadCellError {
            get {
                return ResourceManager.GetString("LoadCellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到模型.
        /// </summary>
        public static string ModelNotFound {
            get {
                return ResourceManager.GetString("ModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 星期一.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到上下文.
        /// </summary>
        public static string NoContextFound {
            get {
                return ResourceManager.GetString("NoContextFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到客户.
        /// </summary>
        public static string NoCustomersFound {
            get {
                return ResourceManager.GetString("NoCustomersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到鸡蛋类别.
        /// </summary>
        public static string NoEggCategoriesFound {
            get {
                return ResourceManager.GetString("NoEggCategoriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到许可证.
        /// </summary>
        public static string NoLicenseFound {
            get {
                return ResourceManager.GetString("NoLicenseFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 找不到任何设备.
        /// </summary>
        public static string NoMachineFound {
            get {
                return ResourceManager.GetString("NoMachineFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 找不到机器操作.
        /// </summary>
        public static string NoMachineOperationFound {
            get {
                return ResourceManager.GetString("NoMachineOperationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 找不到时间.
        /// </summary>
        public static string NoMachineScheduleFound {
            get {
                return ResourceManager.GetString("NoMachineScheduleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到班次.
        /// </summary>
        public static string NoShiftFound {
            get {
                return ResourceManager.GetString("NoShiftFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 找不到周计划.
        /// </summary>
        public static string NoWeekScheduledFound {
            get {
                return ResourceManager.GetString("NoWeekScheduledFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 关闭.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 操作.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 密码必须包含至少一个小写字母和一个大写字母.
        /// </summary>
        public static string PasswordMustContainUppercaseAndLowercase {
            get {
                return ResourceManager.GetString("PasswordMustContainUppercaseAndLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 密码必须至少包含一个特殊字符.
        /// </summary>
        public static string PasswordMustHaveSpecialCharacter {
            get {
                return ResourceManager.GetString("PasswordMustHaveSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 密码长度必须在8到50个字符之间.
        /// </summary>
        public static string PasswordMustHaveValidLength {
            get {
                return ResourceManager.GetString("PasswordMustHaveValidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 密码恢复.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 密码不相同.
        /// </summary>
        public static string PasswordsAreNotTheSame {
            get {
                return ResourceManager.GetString("PasswordsAreNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到任何植物.
        /// </summary>
        public static string PlantNotFound {
            get {
                return ResourceManager.GetString("PlantNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 已存在使用此CNPJ的植物.
        /// </summary>
        public static string PlantWithSameCnpjError {
            get {
                return ResourceManager.GetString("PlantWithSameCnpjError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 已存在使用此名称的植物.
        /// </summary>
        public static string PlantWithSameNameError {
            get {
                return ResourceManager.GetString("PlantWithSameNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到产品.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 数量.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 红色.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 注册没有找到.
        /// </summary>
        public static string RegisterNotFound {
            get {
                return ResourceManager.GetString("RegisterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 剩余时间.
        /// </summary>
        public static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 批次不能相同.
        /// </summary>
        public static string SameBatchError {
            get {
                return ResourceManager.GetString("SameBatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 星期六.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 秤.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 计划停止.
        /// </summary>
        public static string ScheduledStop {
            get {
                return ResourceManager.GetString("ScheduledStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 计划停止时间与其他停止时间冲突.
        /// </summary>
        public static string ScheduledStopConflict {
            get {
                return ResourceManager.GetString("ScheduledStopConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 班次A.
        /// </summary>
        public static string ShiftA {
            get {
                return ResourceManager.GetString("ShiftA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 班次B.
        /// </summary>
        public static string ShiftB {
            get {
                return ResourceManager.GetString("ShiftB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 班次C.
        /// </summary>
        public static string ShiftC {
            get {
                return ResourceManager.GetString("ShiftC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 班次安排与其他班次冲突.
        /// </summary>
        public static string ShiftConflict {
            get {
                return ResourceManager.GetString("ShiftConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 班次D.
        /// </summary>
        public static string ShiftD {
            get {
                return ResourceManager.GetString("ShiftD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 小号.
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 电磁阀.
        /// </summary>
        public static string Solenoid {
            get {
                return ResourceManager.GetString("Solenoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 电磁阀错误.
        /// </summary>
        public static string SolenoidError {
            get {
                return ResourceManager.GetString("SolenoidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 备用支持.
        /// </summary>
        public static string StandBy {
            get {
                return ResourceManager.GetString("StandBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 开始日期.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 开始日期不能大于结束日期.
        /// </summary>
        public static string StartDateGreaterThanEndDate {
            get {
                return ResourceManager.GetString("StartDateGreaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 开始.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 机器停止.
        /// </summary>
        public static string StoppedMachine {
            get {
                return ResourceManager.GetString("StoppedMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 任何名称都不能超过15个字符.
        /// </summary>
        public static string StringLengthValidation {
            get {
                return ResourceManager.GetString("StringLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 星期日.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 过大号.
        /// </summary>
        public static string SuperJumbo {
            get {
                return ResourceManager.GetString("SuperJumbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 星期四.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a API请求过多。请稍候.
        /// </summary>
        public static string TooManyRequestsWaitAMoment {
            get {
                return ResourceManager.GetString("TooManyRequestsWaitAMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 箱子数量.
        /// </summary>
        public static string TotalBoxesQuantity {
            get {
                return ResourceManager.GetString("TotalBoxesQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 一般数据.
        /// </summary>
        public static string TotalEggsDataTitle {
            get {
                return ResourceManager.GetString("TotalEggsDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 鸡蛋数量.
        /// </summary>
        public static string TotalEggsQuantity {
            get {
                return ResourceManager.GetString("TotalEggsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 机器总产量.
        /// </summary>
        public static string TotalMachineProducing {
            get {
                return ResourceManager.GetString("TotalMachineProducing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 计划外停机时间总计.
        /// </summary>
        public static string TotalUnscheduledDowntime {
            get {
                return ResourceManager.GetString("TotalUnscheduledDowntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 总重量.
        /// </summary>
        public static string TotalWeight {
            get {
                return ResourceManager.GetString("TotalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 星期二.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 非计划停机.
        /// </summary>
        public static string UnscheduledStop {
            get {
                return ResourceManager.GetString("UnscheduledStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 找不到用户.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 用户时段已过期.
        /// </summary>
        public static string UserSessionExpired {
            get {
                return ResourceManager.GetString("UserSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 没有权限的用户.
        /// </summary>
        public static string UserWithoutPermission {
            get {
                return ResourceManager.GetString("UserWithoutPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 已存在使用此文档的用户.
        /// </summary>
        public static string UserWithSameDocumentError {
            get {
                return ResourceManager.GetString("UserWithSameDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 已存在使用此电子邮件的用户.
        /// </summary>
        public static string UserWithSameEmailError {
            get {
                return ResourceManager.GetString("UserWithSameEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 已存在使用此密钥的用户.
        /// </summary>
        public static string UserWithSameKeyError {
            get {
                return ResourceManager.GetString("UserWithSameKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 有效的令牌已生成.
        /// </summary>
        public static string ValidTokenAlreadyGenerated {
            get {
                return ResourceManager.GetString("ValidTokenAlreadyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 值.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 未找到视觉系统.
        /// </summary>
        public static string VisionSystemNotFound {
            get {
                return ResourceManager.GetString("VisionSystemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 视觉系统.
        /// </summary>
        public static string VisionSystemTitle {
            get {
                return ResourceManager.GetString("VisionSystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 请等待五分钟后再次发送电子邮件.
        /// </summary>
        public static string WaitFiveMinutesToSendEmailAgain {
            get {
                return ResourceManager.GetString("WaitFiveMinutesToSendEmailAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 星期三.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 重量.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 白色.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 您的恢复代码是.
        /// </summary>
        public static string YourRecoveryCodeIs {
            get {
                return ResourceManager.GetString("YourRecoveryCodeIs", resourceCulture);
            }
        }
    }
}
